language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.2.1
  - jruby-head
  - rbx-2
script: bundle exec rspec spec
matrix:
  allow_failures:
before_install:
  - git clone git://github.com/nanomsg/nanomsg.git
  - cd nanomsg && ./autogen.sh && ./configure && sudo make install && sudo ldconfig && cd ${TRAVIS_BUILD_DIR}
